### ISSUE TITLE
Duplicated services in manifest

### ISSUE THREAD

**Issue by anthon** [swiss-art-research-net/sari-iiif-manifest-service#8]
https://skkg-iiif.swissartresearch.net/manifest/object/ffac63c7-3f63-4b36-a8e3-2688e5ecf924 <= this manifest has 496 pages, and the absolute bulk of them are one of two images, multiple times:
- https://iiif.skkg.3ms.io/iiif/2/1da531d2-bae2-4319-b89d-05de5ace47af_p0002
- https://iiif.skkg.3ms.io/iiif/2/1da531d2-bae2-4319-b89d-05de5ace47af

Here you see it live, for reference: https://staging.skkg.azt.pink/de/filters/skkg%3Aobject%2Fffac63c7-3f63-4b36-a8e3-2688e5ecf924

**Comment by fkraeutli** [comment]
Fixed (missing DISTINCT in SPARQL image query)
